# Generated by Django 4.2.6 on 2023-10-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
        ('airlane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=30)),
                ('To', models.CharField(max_length=30)),
                ('airlane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airlane.airlane')),
                ('plane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plane.plane')),
            ],
        ),
    ]
